site_name: AERO-OPTIM
site_url: https://mschouler.github.io/aero-optim/
repo_url: https://github.com/mschouler/aero-optim
site_dir: public
# site_favicon: path/to/favicon
nav:
  - Home: index.md
  - About: about.md
theme: 
  name: readthedocs
  # logo: path/to/logo
  # favicon: path/to/avatar

extra_javascript: 
    - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-AMS-MML_HTMLorMML
